### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#1]

**Comment by asmisha** [comment]
Жду шрифтов

**Comment by Eugeny** [comment]
[Akkurat Regular.zip](https://github.com/asmisha/awesome-crm/files/542775/Akkurat.Regular.zip)
[Akkurat-Bold.zip](https://github.com/asmisha/awesome-crm/files/542776/Akkurat-Bold.zip)

P.S. съехал лейаут немного
![selection_125](https://cloud.githubusercontent.com/assets/161476/19576062/e5891022-9711-11e6-9418-fdd34b0032f6.png)

**Comment by asmisha** [comment]
Что касается съехавшего лэйаута, то тут сложно сказать, в чем причина - в стилях страницы задана константой высота страницы а4, у тебя страница выше, получается
Если это поможет, то без генерации пдф, можно смотреть урл генерации пдф с "?html=1" в конце. Класс .page отвечает за расположение страницы

```
        pageSize: 'A4',
        T: 0,
        B: 0,
        L: 0,
        R: 0
```
Вот такие параметры я передаю wkhtmltopdf, чтобы управлять размерами и отступами

**Comment by Eugeny** [comment]
Посмотрел, так там размер .page не тот. А4 = 210×297 мм.
Проще наверное сделать картинкой с `position: fixed`

**Comment by asmisha** [comment]
Не совсем, если я не угадал размер, то страницы неправильно поделятся. Я так и подбирал размеры эти. Ну и кроме того, видишь, если бы у тебя еще меньше высота была, то лого было бы еще выше.

**Comment by Eugeny** [comment]
У меня вообще весь pdf получается подозрительно мелкий по сравнению с шаблоном. У тебя какая версия wkhtmltopdf?

**Comment by Eugeny** [comment]
Я взял bleeding edge из http://wkhtmltopdf.org/downloads.html

**Comment by asmisha** [comment]
wkhtmltopdf 0.12.3 (with patched qt)
BE нет по osx

**Comment by Eugeny** [comment]
Ты что-нибудь менял касательно pdf в последних коммитах? Я переустановил wkhtmltopdf по http://stackoverflow.com/questions/34479040/how-to-install-wkhtmltopdf-with-patched-qt и теперь все ок.

**Comment by asmisha** [comment]
Нет, ничего не менял. Может как раз дело в patched qt?

**Comment by Eugeny** [comment]
Может быть

**Comment by Eugeny** [comment]
AFAIK пустая страница в конце не нужна, картинка должна быть на последней странице с контентом.

**Comment by Eugeny** [comment]
UPD: картинка внизу точно на последней с контентом, лого вверху справа на каждой

**Comment by Eugeny** [comment]
:+1:
