### ISSUE TITLE
Заменить list-group на btn-group в списках с несколькими кнопками

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#18]
Экономим место
![selection_139](https://cloud.githubusercontent.com/assets/161476/19688110/8a4059fe-9ac8-11e6-9bd3-f2785335731f.png)

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19851180/9ae9a52c-9f6d-11e6-8b3b-cf62dc06f6e6.png)
Оставил только тут, т.к. с btn-group еще больше места займется вроде. ок?

**Comment by Eugeny** [comment]
Давай тут сделаем в две строки, т.к. поля уже тоже слишком мелкие

<ng-repeat-start>
ID
Name, type
Description (rowspan=2)
Price+currency сверху (currency можно сделать шириной в 1 символ), Purchase price снизу
Amount
Discount
.fa.fa-plus Machine
.fa-trash-o
<ng-repeat-end>

**Comment by asmisha** [comment]
Не понял, как именно поделить поля по строкам. Какие вниз, какие вверх?

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19852453/6efa9f8c-9f74-11e6-9d29-987270c9dd36.png)
такого примерно плана что-то должно получиться?

**Comment by Eugeny** [comment]
Да, только 1) description растянуть на обе строки (rowspan=2), и 2) price и currency в одной строке.

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19889485/2a7c67b4-a046-11e6-835d-234375a32cce.png)
оставить футер такой, или сделать в одну строку?

**Comment by Eugeny** [comment]
Сделай в футере цены одним столбцом, выровненным по Price/purchase price, как в PDF.

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19889976/16bb967a-a049-11e6-8299-7fba23f39cc4.png)

**Comment by Eugeny** [comment]
Пусть 1 будет.

Еще кой чего: изменим строку создания saleItem. Т.к. редактировать поля уже можно и потом, оставь только Name, на всю ширину, без лейбла (placeholder вместо него) и кнопку Add. Будет хоть меньше с самой таблицей сливаться.
