### ISSUE TITLE
Machines в сайдбаре

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#21]
1) fa fa-server
2) почему-то всегда выделена

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19889009/86c85c88-a043-11e6-8038-13eb17edc6d7.png)
![image](https://cloud.githubusercontent.com/assets/2305853/19889017/9636e306-a043-11e6-87c4-5905ae172a51.png)

Иконку поменял, а выделение у меня только когда нужно.

**Comment by Eugeny** [comment]
Я к тому, почему она всегда белым? Если это из-за того, что верхний уровень, сунь ее в подраздел Sales.

**Comment by asmisha** [comment]
Да, так и есть. Ок.
