### ISSUE TITLE
Изменения в создании Invoice

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#23]
1. Поменять визуально местами расположение блоков Delivery & Invoice в sales и сайдбаре - сначала Delivery, потом Invoice.
2. Delivery создаются так же как и раньше (выборкой saleitem из ордера), а Invoice - _выборкой из списка delivery_. Т.е: "new invoice" -> проставить галки на списке из всех delivery в sale -> создается инвойс со всеми saleitem из выбранных delivery.

**Comment by asmisha** [comment]
> Поменять визуально местами расположение блоков Delivery & Invoice в sales и сайдбаре - сначала Delivery, потом Invoice.

Сейчас так и есть, видимо, нужно наоборот - сначала Invoice, потом Delivery?

**Comment by Eugeny** [comment]
Если так и есть, то все ок. Показалось.

**Comment by Eugeny** [comment]
Соответственно, пока нет ни одной Delivery, нельзя создать инвойс
