### ISSUE TITLE
В диалоге создания Delivery все ID почему-то отсчитываются от 2

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#26]

**Comment by Eugeny** [comment]
![selection_145](https://cloud.githubusercontent.com/assets/161476/19889706/af68d9cc-a036-11e6-9f43-c6b82509474f.png)

**Comment by asmisha** [comment]
Это поле приходит из бд, у меня тат MongoId вообще

**Comment by Eugeny** [comment]
Так это же номер в документе должен быть

**Comment by asmisha** [comment]
Ну могу просто на нумерацию от 1 поменять

**Comment by Eugeny** [comment]
Идет.
