### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#30]
People: выбор сортировки по имени или фамилии

**Comment by asmisha** [comment]
Так есть же: 
![image](https://cloud.githubusercontent.com/assets/2305853/20845806/c8280802-b8d7-11e6-9177-a5a5973cd187.png) 
![image](https://cloud.githubusercontent.com/assets/2305853/20845815/d2a06a90-b8d7-11e6-8408-dfb44fcb01c7.png)

**Comment by Eugeny** [comment]
А, тогда надо переименовать в Sort by surname.
