### ISSUE TITLE
Sidebar layout

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#4]
-Contacts-
* [Companies]
* [People]

-Products-
* [Warehouse] aka Parts
* [Products] aka product templates
* [Part types]

-Sales-
* [Projects] aka Sales
* [Offers]
* [Orders]
* [Deliveries]
* [Invoices]

Подкатегории не должны закрываться после клика на ссылку

И добавь какие-нибудь иконки (по желанию), чтобы вопросы не висели

**Comment by asmisha** [comment]
А у тебя может есть рецептик, как сделать, чтобы подкатегории не закрывались? Если нет, буду дальше искать, пока нашел только нерабочие гряхные хаки.

**Comment by Eugeny** [comment]
А это что вообще за компонент?
Сделай их просто на верхнем уровне все

**Comment by Eugeny** [comment]
Да и просто жестко сверстать можно. Категории в этом списке не нужно делать сворачивающимися
