### ISSUE TITLE
Импорт из JSON

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#44]
Нужен скрипт для импорта данных из json-дампа старой CRM

* `Company.comment` -> импортировать как один комментарий без автора
* `Contact.is_company_contact` -> если true, то этот Contact - `contactPerson` своей Company.
* `Project.internal_contact_id` -> `Sale.salesLead`
* `Project.contact_id` -> `Sale.companyContact`
* `Project.topic`, `Project.throughput`, `Project.product`, `Project.num_clients_san`, `Project.num_clients_nas` -> `Sale.description`
* `File` -> преобразовать в комментарии с прикрепленными файлами. Скажи потом, как разложить сами файлы в uploads...

Данные: https://gist.githubusercontent.com/Eugeny/a68ee8f5d12f64c0f579391dc16e5f2c/raw/6ed89e6ce52ce44e5973f103ad7b6c0b84ce3e35/1.json

**Comment by Eugeny** [comment]
0: description в `comment`, а комменты из json - в комментарии, см п. 2
1: давай добавим поле Date в Sale, для новых Sale пусть устанавливается в текущую дату
2, 3: тогда нужно добавить возможность комментирования туда - см также #42
4, 5: исправлю
6: Добавь форму коммента с загрузкой файлов к machine и sale (см. п. 2,3). Пути у меня у самого в базе не хранятся - сделай чтобы они просто лежали в `./uploads/<id>`, я файлы потом скриптом разложу

**Comment by asmisha** [comment]
1. у тебя это текстовое поле, т.е. я там видел не только даты в формате дат (см скрин)
![image](https://cloud.githubusercontent.com/assets/2305853/21982954/c70b3df4-dbff-11e6-958f-1f99a901a729.png)

6. я не сохраняю твои id, могу вывести тогда мэппинг oldId => newId

**Comment by Eugeny** [comment]
Тогда давай дату просто добавим к описанию Sale внизу. Соответствие id можно в json вывести отдельный

**Comment by Eugeny** [comment]
Исправил данные https://gist.githubusercontent.com/Eugeny/f2f3dc0597630c4b8d9573acbfc3fc4e/raw/64f8469c8b536b7e7e87fc49784857f57901ff77/1.json

**Comment by asmisha** [comment]
@Eugeny 

> 3. Не понял твой первый пункт про Company.comment - такого поля в импорте нет, а comments в импорте с компаниями не связан.

**Comment by Eugeny** [comment]
Сорри, проглядел. У компаний действительно нет комментов.
7. поставь всем `123`
8. Является юзер админом. Если у тебя сейчас нет никаких сверх-прав для отдельных юзеров, то можно выкинуть.

**Comment by asmisha** [comment]
и по поводу файлов еще
6. расширение какое у файлов?

**Comment by Eugeny** [comment]
в фс - можно без расширения

**Comment by Eugeny** [comment]
добавил оригинальные имена файлов https://gist.githubusercontent.com/Eugeny/f2f3dc0597630c4b8d9573acbfc3fc4e/raw/a9bdd33c590c9ef285d6e583254af0fedb42b05b/1.json

**Comment by asmisha** [comment]
Тут все готово, только пользователи почему-то криво авторизовываются (ЗЫ пароль 123456789), поковыряю еще

**Comment by Eugeny** [comment]
вроде работает
