### ISSUE TITLE
Purchase price

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#5]
"Purchase price" field for: 
* Product templates (sum of PartType prices by default, editable by user)
* SaleItem (purchasePrice of the SaleItem's ProductTemplate by default if provided, editable by user)
* Every document type, visible and editable for each SaleItem, but not visible in the exported PDFs

**Comment by asmisha** [comment]
@Eugeny 
> Every document type, visible and editable for each SaleItem, but not visible in the exported PDFs
так для документов, или SaleItem'ов?

**Comment by Eugeny** [comment]
SaleItem'ов

**Comment by asmisha** [comment]
@Eugeny 
> Product templates (sum of PartType prices by default, editable by user)
SaleItem (purchasePrice of the SaleItem's ProductTemplate by default if provided, editable by user)

У этих уже есть price, речь об этом поле, или о новом?

**Comment by Eugeny** [comment]
Purchase Price (стоимость закупки у поставщика) - отдельное поле рядом с price, которое видно юзерам но не видно клиенту в pdf
