### ISSUE TITLE
Prices

### ISSUE THREAD

**Issue by Eugeny** [asmisha/awesome-crm#6]
Price calculations for the documents

For the documents except Delivery, show "Total price", "Discount", "Net price" and "Purchase price" below the table.

Net price (Nettopreis in the PDFs) = sum of each SaleItems' price
Discount (Rabatt in the PDFs) = a field on the document itself, switchable between integer value in percents and integer value in the document's currency
Total price (Preis in the PDFs) = ``netPrice * (1.0 - discount / 100) * (1 + (vatEligible ? VAT_RATE : 0))``
Purchase price (hidden from PDFs) = sum of each SaleItems' purchasePrice
VAT_RATE = 0.19
All 4 fields are autocalculated by default but editable by user

vatEligible is an editable boolean field on each document, prefilled from company.vatEligible

**Comment by asmisha** [comment]
> Discount (Rabatt in the PDFs) = a field on the document itself, switchable between integer value in percents and integer value in the document's currency

@Eugeny Currently each sale item has its own discount - should I remove it?

**Comment by Eugeny** [comment]
Не, скидки и у документа в целом, и у отдельных итемов.

**Comment by asmisha** [comment]
Total Price расчитывается из какой скидки?

**Comment by Eugeny** [comment]
Спросил, есть изменения: поле скидки ТОЛЬКО на SaleItem. 
Строка SaleItem выглядит теперь так:

id - старые поля - price (input) - discount% (input) - [price-discount] (только отображение, только если есть discount)

В PDF исходные цены без скидки не видны, т.е.

id - старые поля - discount% - [price-discount]

----------

Discount под таблицей соответственно не нужен.
netPrice = `sum(x.price - x.discount for x in .saleitems)`
totalPrice = `netPrice * (1 + (vatEligible ? VAT_RATE : 0))`

**Comment by asmisha** [comment]
>Discount под таблицей соответственно не нужен.
netPrice = sum(x.price - x.discount for x in .saleitems)
totalPrice = netPrice * (1 + (vatEligible ? VAT_RATE : 0))

т.е. скидка теперь в деньгах, не в процентах?

**Comment by Eugeny** [comment]
В процентах, я уже не расписывал вычисление

**Comment by asmisha** [comment]
@Eugeny полей таких в пдф нет, там внизу 
Zwischensumme
zuzüglich
Gesamtsumme
это, я так понимаю, net price, vat, total price?

**Comment by Eugeny** [comment]
Zwischensumme меняем в шаблоне на `Nettopreis` и отображаем netPrice
zuzüglich $VAT_RATE% MwSt. = `netPrice * VAT_RATE`. Если не sale.company.vatEligible то строку можно не показывать
Gesamtsumme - и есть total price

**Comment by Eugeny** [comment]
Еще вот что: в шаблоне Einzelprice = saleitem.price до скидки - оставляем, а Gesamtpreis в строке - общая цена со скидкой (и количество тоже учитываем!)

Инфо про скидку лучше добавить снизу описания (напр `Discount: X%`), чтобы не растягивать шаблон

**Comment by asmisha** [comment]
![image](https://cloud.githubusercontent.com/assets/2305853/19682597/068c603c-9ab7-11e6-96ff-40b4da4711e5.png)
сейчас так, скидка в принципе не растягивает ничего

**Comment by Eugeny** [comment]
отлично

**Comment by Eugeny** [comment]
Справа, где ID документа:

Offer = Angebot / Angebotsdatum
Order = Bestellung / Bestellungsdatum
Invoice = Rechnung / Rechnungsdatum
Delivery = Lieferschein / Lieferscheindatum (без s)

**Comment by Eugeny** [comment]
Скидка не учлась
![selection_132](https://cloud.githubusercontent.com/assets/161476/19687502/e17b4b82-9ac5-11e6-801e-9bad3acc37e9.png)
